# Generated by Django 3.2.9 on 2021-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='label',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Text'),
        ),
    ]
